import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { createProductClient } from "../api/productClient";
import { IssueList } from "../components/analysis/IssueList";
import { ArtifactList } from "../components/product/ArtifactList";
import { ErrorState } from "../components/product/ErrorState";
import { EvidenceSummary } from "../components/product/EvidenceSummary";
import { LoadingSkeleton } from "../components/product/LoadingSkeleton";
import { PageHeader } from "../components/product/PageHeader";
import { SectionPanel } from "../components/product/SectionPanel";
import type { AnalysisRun, EvidenceRecord, IssueRecord } from "../types/product";
const labels:Record<string,string>={running:"Analysis running",queued:"Analysis queued",completed:"Analysis completed",failed:"Analysis failed",evidence_incomplete:"Evidence incomplete"};
export function AnalysisRunPage(){const {runId=""}=useParams();const [run,setRun]=useState<AnalysisRun>();const [issues,setIssues]=useState<IssueRecord[]>([]);const [records,setRecords]=useState<EvidenceRecord[]>([]);const [artifacts,setArtifacts]=useState<string[]>([]);const [errors,setErrors]=useState<unknown[]>([]);useEffect(()=>{let active=true;const c=createProductClient();Promise.allSettled([c.getAnalysis(runId),c.getAnalysisIssues(runId),c.getAnalysisEvidence(runId),c.getAnalysisBundle(runId)]).then(rs=>{if(!active)return;if(rs[0].status==="fulfilled")setRun(rs[0].value);if(rs[1].status==="fulfilled")setIssues(rs[1].value.issues);if(rs[2].status==="fulfilled")setRecords(rs[2].value.records);if(rs[3].status==="fulfilled")setArtifacts(rs[3].value.artifacts);setErrors(rs.filter(x=>x.status==="rejected").map(x=>(x as PromiseRejectedResult).reason))});return()=>{active=false}},[runId]);return <><PageHeader eyebrow={`Analysis / ${runId}`} title="Analysis run" description="Constraint findings, indexed evidence, and reproducible artifacts."/>{!run&&!errors.length?<LoadingSkeleton label="Loading analysis"/>:null}{run?<><div className={`run-state run-state--${run.status}`}>{labels[run.status]||run.status}<code title={run.analysis_run_id}>{run.analysis_run_id}</code></div>{run.hard_constraint_passed===false?<div className="constraint-failed">Hard constraint failed</div>:null}<EvidenceSummary boundary={run.evidence_boundary}/></>:null}{errors.map((e,i)=><ErrorState key={i} error={e} compact/>)}<div className="analysis-grid"><SectionPanel title="Issues"><IssueList issues={issues}/></SectionPanel><SectionPanel title="Evidence index"><ul className="evidence-list">{records.map(r=><li key={r.evidence_id}><strong>{r.evidence_type}</strong><code>{r.source_ref}</code></li>)}</ul></SectionPanel></div><SectionPanel title="Read-only candidates" description="Suggestions require a new simulation run before any engineering claim."><p className="readonly-note">Read-only suggestion · must_resimulate = true</p></SectionPanel><SectionPanel title="Artifacts"><ArtifactList artifacts={artifacts}/></SectionPanel></>}
